version: '3.8'

services:
  mongo:
    image: mongo:7.0.4-jammy@sha256:8c2d2f7fe8738b97c9836c9c004d70862abe665baedbcd6cd1f74c7ce89a9cc4
    ports:
      - "27017:27017/tcp"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: stella

  mongo-express:
    image: mongo-express:1.0.0-20@sha256:ed111ae0c75abea5d53984a419f55df8bbab7dfae8df7d1e64adab5a9610468d
    ports:
      - "8081:8081/tcp"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017

  backend:
    image: golang:1.21.5-bookworm@sha256:2d3b13c2a6368032e9697e64e7c923184e6e3be03cf01eadff27de124114e64e
    working_dir: /app/backend
    command: make dev
    ports:
      - "8080:8080/tcp"
    volumes:
      - source: .
        target: /app
        type: bind
    environment:
      MONGO_URI: mongodb://root:password@mongo:27017/stella
