version: '3.8'

services:
  mongo:
    image: mongo:7.0.5-jammy@sha256:635bd7db1921f7ede76d4a8ba9c16e37cbdf6cb895a1350b82fb9fa8ebfa5f47
    ports:
      - "27017:27017/tcp"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: stella

  mongo-express:
    image: mongo-express:1.0.0-20@sha256:ed111ae0c75abea5d53984a419f55df8bbab7dfae8df7d1e64adab5a9610468d
    ports:
      - "8081:8081/tcp"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017

  backend:
    image: golang:1.21.6-bookworm@sha256:688ad7f282ce711cc28676531f45d5b840790e28a689fbd4e8e4ac181e23e9c4
    working_dir: /app/backend
    command: make dev
    ports:
      - "8080:8080/tcp"
    volumes:
      - source: .
        target: /app
        type: bind
    environment:
      MONGO_URI: mongodb://root:password@mongo:27017/stella
