root = "."
tmp_dir = "tmp"

[build]
args_bin = []
bin = ""
cmd = "go build -o ./tmp/main ./cmd/server"
delay = 0
exclude_dir = []
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = true
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = true
poll_interval = 1000
rerun = false
rerun_delay = 500
send_interrupt = true
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
