import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { Container } from 'react-bootstrap'

import TopPanel from '../components/panel'
import { DEFAULT_SETTINGS, Settings } from '../lib/settings'
import { useLocalStorage } from '../lib/useLocalStorage'

export const LOCAL_STORAGE_KEY = 'stella-settings' as const

export type AppProps = {
  readonly settings: Settings
  readonly setSettings: React.Dispatch<React.SetStateAction<Settings>>
}

const Home: NextPage = () => {
  const [settings, setSettings] = useLocalStorage<Settings>(LOCAL_STORAGE_KEY, DEFAULT_SETTINGS)

  return (
    <Container>
      <Head>
        <title>Favorites | stella</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <TopPanel settings={settings} setSettings={setSettings} />
    </Container>
  )
}

export default Home
